- match:
    dependency_type: all
    update_type: semver:minor # includes patch updates!

- match:
    dependency_name: /sentry-.*/
    update_type: all

- match:
    dependency_name: the # Bump *the* sentry-javascript group with X updates
    update_type: all
