plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_from:
  - .rubocop/layout.yml
  - .rubocop/lint.yml
  - .rubocop/metrics.yml
  - .rubocop/performance.yml
  - .rubocop/rails.yml
  - .rubocop/rspec.yml
  - .rubocop/style.yml
  - .rubocop_todo.yml

AllCops:
  UseCache: True
  NewCops: enable
  MigratedSchemaVersion: 20240930231316
  Exclude:
    - 'bin/*'
    - 'db/*schema.rb'
    - 'vendor/**/*'
    # Ignore local files for faster processing
    - 'tmp/**/*'
    - 'out/**/*'
    - 'node_modules/**/*'
    - 'coverage/**/*'
