{
 "title": "CodeOcean Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "codemoon" }
  ]
 },
 "panels": [
  {
   "title": "Amount of Submissions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus\" and\n    r._field == \"instance_count\" and\n    r.class == \"Submission\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r.class}))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "External Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus\" and\n    r._field == \"instance_count\" and\n    r.class == \"ExternalUser\"\n  )\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Internal Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus\" and\n    r._field == \"instance_count\" and\n    r.class == \"InternalUser\"\n  )\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Exercises", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Exercises",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus\" and\n    r._field == \"instance_count\" and\n    r.class == \"Exercise\"\n  )\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Execution Environments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus\" and\n    r._field == \"instance_count\" and\n    r.class == \"ExecutionEnvironment\"\n  )\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exercise Collections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus\" and\n    r._field == \"instance_count\" and\n    r.class == \"ExerciseCollection\"\n  )\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Submissions per Exercise",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus\" and\n    r._field == \"instance_count\" and\n    (r.class == \"Submission\" or r.class == \"Exercise\")\n  )\n  |> group(columns: [\"class\"])\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Submission Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start:-1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus\" and\n    r._field == \"instance_count\" and\n    r.class == \"Submission\"\n  )\n  |> increase()\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Submissions per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus\" and\n    r._field == \"instance_count\" and\n    r.class == \"Submission\"\n  )\n  |> aggregateWindow(every: 1m, fn: last)\n  |> difference(columns: [\"_value\"], nonNegative: true)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Submissions\"}))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Container Requests per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"codemoon\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus\" and\n    r._field == \"instance_count\" and\n    r.class == \"Testrun\"\n  )\n  |> aggregateWindow(every: 1m, fn: last)\n  |> difference(columns: [\"_value\"], nonNegative: true)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Container Requests\"}))\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Request For Comments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Comments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus\" and\n    r._field == \"instance_count\" and\n    r.class == \"Comment\"\n  )\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request For Comments Ratio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 10, "x": 5, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"codemoon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rfc_count\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r.state}))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RFC count ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"codemoon\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus\" and\n    r._field == \"rfc_count\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r.state}))\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request For Comments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus\" and\n    r._field == \"instance_count\" and\n    r.class == \"RequestForComment\"\n  )\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RFCs with Comments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus\" and\n    r._field == \"rfc_commented_count\"\n  )\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}